[build]
  command = "chmod +x ./netlify-build.sh && ./netlify-build.sh"
  publish = "dist"

[[headers]]
  for = "/pkg/*.wasm"
  [headers.values]
  Content-Type = "application/wasm"
  Cache-Control = "public, max-age=31536000, immutable"
  
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/pkg/*.js"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

